// <auto-generated />
using System;
using IntegratorSofttek.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegratorSofttek.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20230912025505_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IntegratorSofttek.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("project_address");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("project_deletedTimeUtc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("project_isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("project_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("project_status");

                    b.HasKey("Id");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            IsDeleted = false,
                            Name = "Project 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            IsDeleted = false,
                            Name = "Project 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            IsDeleted = false,
                            Name = "Project 3",
                            Status = 0
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("service_deletedTimeUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("service_description");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float")
                        .HasColumnName("service_hourlyRate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("service_isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("service_isDeleted");

                    b.HasKey("Id");

                    b.ToTable("services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Service 1",
                            HourlyRate = 25.0,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "Service 2",
                            HourlyRate = 30.0,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "Service 3",
                            HourlyRate = 20.0,
                            IsActive = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("user_deletedTimeUtc");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_firstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("user_isDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_password");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dni = "1001010",
                            Email = "pablo@example.com",
                            FirstName = "Pablo",
                            IsDeleted = false,
                            LastName = "Ortiz",
                            Password = "123",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Dni = "213",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Password = "456",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "214",
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            IsDeleted = true,
                            LastName = "Smith",
                            Password = "789",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "315",
                            Email = "eva@example.com",
                            FirstName = "Eva",
                            IsDeleted = false,
                            LastName = "Lee",
                            Password = "567",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "416",
                            Email = "john@example.com",
                            FirstName = "John",
                            IsDeleted = true,
                            LastName = "Doe",
                            Password = "901",
                            Type = 0
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("work_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cost")
                        .HasColumnType("float")
                        .HasColumnName("work_cost");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("work_date");

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("work_deletedTimeUtc");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float")
                        .HasColumnName("work_hourlyRate");

                    b.Property<int>("HoursQuantity")
                        .HasColumnType("int")
                        .HasColumnName("work_hoursQuantity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("work_isDeleted");

                    b.Property<int>("Project")
                        .HasColumnType("int");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1000.0,
                            Date = new DateTime(2023, 9, 11, 23, 55, 5, 666, DateTimeKind.Local).AddTicks(6921),
                            HourlyRate = 25.0,
                            HoursQuantity = 40,
                            IsDeleted = false,
                            Project = 1,
                            Service = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 900.0,
                            Date = new DateTime(2023, 9, 10, 23, 55, 5, 666, DateTimeKind.Local).AddTicks(6935),
                            HourlyRate = 30.0,
                            HoursQuantity = 30,
                            IsDeleted = false,
                            Project = 2,
                            Service = 2
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1000.0,
                            Date = new DateTime(2023, 9, 9, 23, 55, 5, 666, DateTimeKind.Local).AddTicks(6939),
                            HourlyRate = 20.0,
                            HoursQuantity = 50,
                            IsDeleted = false,
                            Project = 1,
                            Service = 3
                        },
                        new
                        {
                            Id = 4,
                            Cost = 980.0,
                            Date = new DateTime(2023, 9, 8, 23, 55, 5, 666, DateTimeKind.Local).AddTicks(6940),
                            HourlyRate = 28.0,
                            HoursQuantity = 35,
                            IsDeleted = false,
                            Project = 2,
                            Service = 1
                        },
                        new
                        {
                            Id = 5,
                            Cost = 990.0,
                            Date = new DateTime(2023, 9, 7, 23, 55, 5, 666, DateTimeKind.Local).AddTicks(6941),
                            HourlyRate = 22.0,
                            HoursQuantity = 45,
                            IsDeleted = false,
                            Project = 3,
                            Service = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
