// <auto-generated />
using System;
using IntegratorSofttek.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegratorSofttek.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IntegratorSofttek.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "123 Main St",
                            Name = "Project 1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Adress = "456 Elm St",
                            Name = "Project 2",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            Adress = "789 Oak St",
                            Name = "Project 3",
                            Status = 1
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Service 1",
                            HourlyRate = 25.0,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Service 2",
                            HourlyRate = 30.0,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Service 3",
                            HourlyRate = 20.0,
                            Status = false
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DeletedTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("user_deletedTimeUtc");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_firstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("user_isDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("user_password");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "1001010",
                            Email = "pablo@example.com",
                            FirstName = "Pablo",
                            IsDeleted = false,
                            LastName = "Ortiz",
                            Password = "123",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "213",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Password = "456",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "214",
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            IsDeleted = true,
                            LastName = "Smith",
                            Password = "789",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "315",
                            Email = "eva@example.com",
                            FirstName = "Eva",
                            IsDeleted = false,
                            LastName = "Lee",
                            Password = "567",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            DeletedTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dni = "416",
                            Email = "john@example.com",
                            FirstName = "John",
                            IsDeleted = true,
                            LastName = "Doe",
                            Password = "901",
                            Type = 1
                        });
                });

            modelBuilder.Entity("IntegratorSofttek.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<int>("HoursQuantity")
                        .HasColumnType("int");

                    b.Property<int>("project")
                        .HasColumnType("int");

                    b.Property<int>("service")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1000.0,
                            Date = new DateTime(2023, 9, 11, 12, 8, 12, 728, DateTimeKind.Local).AddTicks(2287),
                            HourlyRate = 25.0,
                            HoursQuantity = 40,
                            project = 0,
                            service = 0
                        },
                        new
                        {
                            Id = 2,
                            Cost = 900.0,
                            Date = new DateTime(2023, 9, 10, 12, 8, 12, 728, DateTimeKind.Local).AddTicks(2300),
                            HourlyRate = 30.0,
                            HoursQuantity = 30,
                            project = 0,
                            service = 0
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1000.0,
                            Date = new DateTime(2023, 9, 9, 12, 8, 12, 728, DateTimeKind.Local).AddTicks(2304),
                            HourlyRate = 20.0,
                            HoursQuantity = 50,
                            project = 0,
                            service = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
